[project]
name = "han-strokes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7, <=3.9.22"
dependencies = [
    "pillow>=9.5.0",
    "pyqt5-tools>=5.15.9.3.3",
    "reportlab>=4.4.2",
    "rlpycairo>=0.3.0",
    "svglib>=1.5.1",
]
